---
- hosts: server
  user: vagrant
  sudo: True

  vars:
    project_name: 'psv'
    mysql_pwd: 12345

  tasks:
    - name: install locales
      apt: pkg=$item state=installed
      with_items:
        - language-pack-de-base
        - language-pack-de
        - locales

    - name: generate locales
      shell: sudo locale-gen

    - name: install essentials
      apt: pkg=$item state=installed
      with_items:
        - php5-mysql
        - php5-mcrypt
        - php-pear
        - php5-dev
        - php5-cli
        - libapache2-mod-php5
        - apache2
        - mysql-server
        - python-mysqldb

    - name: mod rewrite aktivieren
      shell: sudo a2enmod rewrite

    - name: add mysql user
      mysql_user: name=mysql password=$mysql_pwd priv=*.*:ALL state=present

    - name: add wordpress db
      mysql_db: name=wordpress state=present login_user=mysql login_password=$mysql_pwd

    - name: add v-host
      template: src=templates/vhost dest=/etc/apache2/sites-available/$project_name mode=0600 owner=vagrant

    - name: activate v-host
      shell: sudo a2ensite $project_name
      notify: restart apache


  handlers:
    - name: restart php
      service: name=php5-fpm state=restarted

    - name: restart apache
      service: name=apache2 state=restarted
